-- -*- coding: utf-8 -*-
-- Created by Luis Fuentes

USE WAREHOUSE BI_WH_XS;
USE CC_TEST.CC_DW;

-- 1.- Creating file format
CREATE OR REPLACE FILE FORMAT FILE_GENERIC
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    VALIDATE_UTF8 = FALSE
    TRIM_SPACE = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    NULL_IF = ('null', '');

-- 2.- Creating external stage
CREATE OR REPLACE STAGE STAGE_FILE_GENERIC
  FILE_FORMAT = FILE_GENERIC;

PUT file://C:\Users\lf188653\Desktop\Projects\work\EA\DataEngineering-PythonSnowflakeEnv\data\page* @STAGE_FILE_GENERIC AUTO_COMPRESS=true;

LIST @STAGE_FILE_GENERIC;

CREATE OR REPLACE TABLE T_AP_TERMS_STG (
    ROW_ID VARCHAR(255) NULL,
    TERM_ID VARCHAR(255) NULL,
    LAST_UPDATE_DATE VARCHAR(255) NULL,
    LAST_UPDATED_BY VARCHAR(255) NULL,
    CREATION_DATE VARCHAR(255) NULL,
    CREATED_BY VARCHAR(255) NULL,
    LAST_UPDATE_LOGIN VARCHAR(255) NULL,
    ENABLED_FLAG VARCHAR(255) NULL,
    DUE_CUTOFF_DAY VARCHAR(255) NULL,
    TYPE VARCHAR(255) NULL,
    START_DATE_ACTIVE VARCHAR(255) NULL,
    END_DATE_ACTIVE VARCHAR(255) NULL,
    RANK VARCHAR(255) NULL,
    ATTRIBUTE_CATEGORY VARCHAR(255) NULL,
    ATTRIBUTE1 VARCHAR(255) NULL,
    ATTRIBUTE2 VARCHAR(255) NULL,
    ATTRIBUTE3 VARCHAR(255) NULL,
    ATTRIBUTE4 VARCHAR(255) NULL,
    ATTRIBUTE5 VARCHAR(255) NULL,
    ATTRIBUTE6 VARCHAR(255) NULL,
    ATTRIBUTE7 VARCHAR(255) NULL,
    ATTRIBUTE8 VARCHAR(255) NULL,
    ATTRIBUTE9 VARCHAR(255) NULL,
    ATTRIBUTE10 VARCHAR(255) NULL,
    ATTRIBUTE11 VARCHAR(255) NULL,
    ATTRIBUTE12 VARCHAR(255) NULL,
    ATTRIBUTE13 VARCHAR(255) NULL,
    ATTRIBUTE14 VARCHAR(255) NULL,
    ATTRIBUTE15 VARCHAR(255) NULL,
    NAME VARCHAR(255) NULL,
    DESCRIPTION VARCHAR(255) NULL
);

COPY INTO T_AP_TERMS_STG
  FROM @STAGE_FILE_GENERIC
  FILE_FORMAT = (format_name = FILE_GENERIC)
  PATTERN = '.*.gz'
  ON_ERROR = 'skip_file'
  PURGE = TRUE;

--remove @STAGE_FILE_GENERIC pattern='.*gz';

-- Idempotent Operation
DROP STAGE IF EXISTS STAGE_FILE_GENERIC;
DROP FILE FORMAT IF EXISTS FILE_GENERIC;
